import Head from 'next/head';
import { AppLayout, Placeholder } from '@/components';
import Link from 'next/link';
import Board from '@/components/Board/Board';
import Banner from '@/components/Banner/Banner';
import labels from '@/constants/labels.en';

export default function Home() {
  return (
    <>
      <Head>
        <title>Website BRITO</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;1,100;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet"/>
      </Head>
      <AppLayout>
        <Placeholder title='Hero' />
        <Placeholder title='About Us' />
        <Banner title={labels.ourMission.title} description={labels.ourMission.description}/>
        <Banner title={labels.ourVision.title} description={labels.ourVision.description}/>
        <Placeholder title='Our Board' />
        <Board title='dsadsdad'/>
        <Banner title={labels.joinUs.title} description={labels.joinUs.description}/>
        <Placeholder title='Form' />
        <Placeholder title='Contact Us' />
      </AppLayout>
    </>
  );
}