import Head from 'next/head';
import { AppLayout, Placeholder } from '@/components';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Website BRITO</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <AppLayout>
        <Placeholder title='Hero' />
        <Placeholder title='About Us' />
        <Placeholder title='Our Mission' />
        <Placeholder title='Our Vision' />
        <Placeholder title='Our Board' />
        <Placeholder title='Join Us' />
        <Placeholder title='Form' />
        <Placeholder title='Contact Us' />
      </AppLayout>
    </>
  );
}
